# Generated by Django 3.1.7 on 2021-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210403_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
