# Generated by Django 3.1.7 on 2021-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_education_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation',
            field=models.CharField(max_length=20),
        ),
    ]
