# Generated by Django 3.1.7 on 2021-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210404_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Project <built-in function id>', max_length=50),
        ),
    ]
